import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const selectedCountries = [
  "Afghanistan",
  "Guyana",
]

const allCountries = [
  "Cambodia",
  "Russia",
  "Bolivia",
  "Mauritania",
]

function ActionItem({label, action}) {
  return <li>{label} <a href="#" onClick={e => e.preventDefault()} style={{float: "right", marginLeft: "1rem"}}>{action}</a></li>
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Tour Master!
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Selected</h2>
            <ul>
              {selectedCountries.map(c => <ActionItem key={c} label={c} action="-"/>)}
            </ul>
          </div>

          <div className={styles.card}>
            <h2>Choose From</h2>
            <ul>
              {allCountries.map(c => <ActionItem key={c} label={c} action="+"/>)}
            </ul>
          </div>
        </div>

      </main>
    </div>
  )
}
